apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.postgresql.backup.storage }}
  storageClassName: {{ .Values.pvc.postgresql.backup.storageClassName }}
