apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
data:
  nextcloud-username: {{ .Values.secret.nextcloudUsername | b64enc }}
  nextcloud-password: {{ .Values.secret.nextcloudPassword | b64enc }}
  postgresql-username: {{ .Values.secret.postgresqlUsername | b64enc }}
  postgresql-admin-password: {{ .Values.secret.postgresqlAdminPassword | b64enc }} 
  postgresql-user-password: {{ .Values.secret.postgresqlUserPassword | b64enc }}
  smtp-host: {{ .Values.secret.smtpHost | b64enc }}
  smtp-username: {{ .Values.secret.smtpUsername | b64enc }}
  smtp-password: {{ .Values.secret.smtpPassword | b64enc }}
  redis-password: {{ .Values.secret.redisPassword | b64enc }}
