auth:
  existingSecret: shopping-list

persistence:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  enabled: true
  storageClass: longhorn

networking:
  gateway:
    hostname: ''
    parentRefs:
      - name: shared-gateway
        namespace: istio-system
