apiVersion: v1
kind: Endpoints
metadata:
  name: hassio
  namespace: {{ .Values.namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoint.ip }}
  ports:
  - name: hassio
    port: 8123
    protocol: TCP
