{{- $secret := lookup "v1" "Secret" "hassio" "hassio-ingress-secret" -}}
{{- $host0 := "" -}}
{{- if $secret }}
  {{- $host0 = (index $secret.data "ingress-host" | b64dec) -}}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-{{ .Values.ingress.environment }}
    ingress.cilium.io/loadbalancer-mode: shared
  name: hassio
spec:
  ingressClassName: cilium
  rules:
  - host: {{ $host0 }}
    http:
      paths:
      - backend:
          service:
            name: hassio
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $host0 }}
    secretName: hassio-secret
