apiVersion: v1
kind: Service
metadata:
  name: hassio
  namespace: {{ .Values.hassio.namespace }}
spec:
  ports:
  - name: hassio
    port: 443
    protocol: TCP
    targetPort: 8123
  type: ClusterIP
