apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | b64enc }}
  AWS_ENDPOINTS: {{ .Values.secret.awsEndpoints | b64enc }}
