kind: ConfigMap
metadata:
  labels:
    name: metrics-proxy
  name: metrics-proxy-config
  namespace: kube-system
apiVersion: v1
data:
  haproxy.cfg: |
    defaults
      mode http
      timeout connect 5000ms
      timeout client 5000ms
      timeout server 5000ms
      default-server maxconn 10

    frontend kube-controller-manager-frontend
      bind ${NODE_IP}:10252
      http-request deny if !{ path /metrics }
      default_backend kube-controller-manager-backend
    backend kube-controller-manager-backend
      server kube-controller-manager 127.0.0.1:10257 ssl verify none

    frontend kube-scheduler-frontend
      bind ${NODE_IP}:10251
      http-request deny if !{ path /metrics }
      default_backend kube-scheduler-backend
    backend kube-scheduler-backend
      server kube-scheduler 127.0.0.1:10259 ssl verify none

    frontend kube-proxy-frontend
      bind ${NODE_IP}:10249
      http-request deny if !{ path /metrics }
      default_backend kube-proxy-backend
    backend kube-proxy-backend
      server kube-proxy 127.0.0.1:10249

    frontend kube-etcd-frontend
      bind ${NODE_IP}:2381
      http-request deny if !{ path /metrics }
      default_backend kube-etcd-backend
    backend kube-etcd-backend
      server kube-etcd 127.0.0.1:2381
