apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-secret
  namespace: victoriametrics
type: Opaque
data:
  grafana_admin-password: {{ .Values.secret.grafanaAdminPassword | b64enc }}
  grafana_admin-user: {{ .Values.secret.grafanaAdminUser | b64enc }}
