apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: mute-nextcloud-pgdumpall
spec:
  receivers:
    - name: blackhole
  route:
    receiver: blackhole
    matchers:
      # Du kannst hier gewisse Label-Filter setzen, falls sinnvoll
      # z. B. nur Namespace, oder alertgroup
      - namespace = "nextcloud"
      - alertgroup = "general.rules"
    group_interval: 1m
    routes:
      - receiver: blackhole
        matchers:
          - alertgroup = "general.rules"
          - alertname = "InfoInhibitor"
          - exported_alertname = "CPUThrottlingHigh"
          - severity = "none"
