apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: istiod
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istiod

  namespaceSelector:
    matchNames:
      - istio-system

  podMetricsEndpoints:
    - port: http-monitoring
      path: /metrics
      scheme: http

      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_label_app]
          targetLabel: app

        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace

        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod

        - sourceLabels: [__meta_kubernetes_pod_container_name]
          targetLabel: container
