apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: vmrule-alerting-minio
spec:
  groups:
    - name: minio.rules
      rules:
      - alert: NodesOffline
        annotations:
          summary: "Node down in MinIO deployment"
          description: Node(s) in cluster {{`{{$labels.instance}}`}}` offline for more than 5 minutes
        expr: avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m]) > 0
        for: 10m
        labels:
          severity: warn
      - alert: DisksOffline
        annotations:
          summary: "Disks down in MinIO deployment"
          description: Disks(s) in cluster {{`{{$$labels.instance}}`}}` offline for more than 5 minutes
        expr: avg_over_time(minio_cluster_drive_offline_total{job="minio-job"}[5m]) > 0
        for: 10m
        labels:
          severity: warn
