apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: vmrule-alerting-kured
spec:
  groups:
    - name: kured.rules
      rules:
        - alert: RebootRequired
          annotations:
            description: "Machine(s) require being rebooted, probably due to kernel update."
            impact: "Cluster nodes more vulnerable to security exploits. Eventually, no disk space left."
            summary: "Machine(s) require being rebooted, and the reboot daemon has failed to do so for 24 hours"
          expr: max(kured_reboot_required) != 0
          for: 24h
          labels:
            severity: warning
