apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
type: Opaque
data:
  postgresql-admin-password: {{ .Values.secret.postgresqlAdminPassword | b64enc }} 
  postgresql-user-password: {{ .Values.secret.postgresqlUserPassword | b64enc }}
  redis-password: {{ .Values.secret.redisPassword | b64enc }}
