# needed for istio in ambient mode
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: hedgedoc
    app.kubernetes.io/name: hedgedoc
  name: hedgedoc-postgresql-ambient-hbones
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: hedgedoc
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
  - Ingress
  egress:
  - ports:
    - port: 15008
      protocol: TCP
