apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hedgedoc-chart
  namespace: hedgedoc
spec:
  encryptedData:
    CMD_SESSION_SECRET: AgAisQneLkg7zJ2zCb0UtKZDMDVnbArpfSa18qn4XdO/rwM6ciqOnUGaw0zGUmEak7Chw9i0vCBfRiZZPt+CEft8mP/LFxkt+u/lhZR546qO8NfJpRE94Shscl/N+oCFwLr3Wo1uELnm2En84sfGJWdEyeSS77vYFGmkctUib83V40SRMTESUbnM5ayJ/11VEM5rxrtWLIoDN+PNPlGiNqtjVHLCzNlFAE2YRGVgtM2fjKmXzfwXpOrpiSs2qW/hO0Yl5CJ2Xei4oW3w0w/5EC9xZUyN8B0mOQb0vX1Q9e4brH5Wnq/AJR7VQZEVPn33SUuD3vtbhjAotbmi5h40SSWvIgHTPD40+YNdp5w4OFwFFEubElzA7xK5yl6/rVFJweRs+767xfwWHXOBzoZjRd82sAOJPu933b1uhdsoNvVmTLLaVZvXAXPTHUZdwZdsMpGyvUkqkHu/dDRKeC0XRy9pgl72kegUOoVasb7L9yB3v3bkKiNUFvtupL7fjHxdSX030uPLji6Vh8LZ1x7Zdah3KAobUwAGxFmqeusRDvk1p/UX/v4S3DxyZsrB39VHi7NzMOQEosVT59+pHCED2UWA/Bre21ZDZ82Crj0Zmmg414leUUW+7XqA41RNz5vdxdtsJy4zcvo80rxfloiGeke54xg5EciLpShlx8aHxkNF2nHvcs1pwlRQWGXtRXOvh37fZDiY+/akgMte+PKldqXWIAd9gtn83/0sIzyB3VfFeVSc3wehhN0j
  template:
    metadata:
      name: hedgedoc-chart
      namespace: hedgedoc
    type: Opaque
