apiVersion: v1
kind: Secret
metadata:
  name: jdownloader
type: Opaque
data:
  env_jd_devicename: {{ .Values.jd.secret.env_devicename | b64enc }}
  env_jd_email: {{ .Values.jd.secret.env_email | b64enc }}
  env_jd_password: {{ .Values.jd.secret.env_password | b64enc }}
