apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nextcloud
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: {{ .Values.nextcloud.version }}
      helm:
        valueFiles:
          - $values/charts/nextcloud/values.yaml
        parameters:
          - name: "ingress.tls[0].hosts[0]"
            value: {{ .Values.nextcloud.ingress.tls0.hosts0 }}
          - name: "nextcloud.host"
            value: {{ .Values.nextcloud.host }}
          - name: "nextcloud.mail.fromAddress"
            value: {{ .Values.nextcloud.mail.fromAddress }}
          - name: "nextcloud.mail.domain"
            value: {{ .Values.nextcloud.mail.domain }}
          - name: "nextcloud.trustedDomains[0]"
            value: {{ .Values.nextcloud.trustedDomains0 }}
          - name: "nextcloud.extraEnv[0].name"
            value: "OVERWRITEHOST"
          - name: "nextcloud.extraEnv[0].value"
            value: {{ .Values.nextcloud.extraEnv0.overwritehost }}
          - name: "nextcloud.extraEnv[1].name"
            value: "OVERWRITECLIURL"
          - name: "nextcloud.extraEnv[1].value"
            value: {{ .Values.nextcloud.extraEnv1.overwritecliurl }}
          - name: "externalDatabase.database"
            value: {{ .Values.nextcloud.externalDatabase.database }}
          - name: "postgresql.global.postgresql.auth.database"
            value: {{ .Values.nextcloud.postgresql.global.postgresql.auth.database }}
          - name: "postgresql.global.postgresql.auth.username"
            value: {{ .Values.nextcloud.postgresql.global.postgresql.auth.username }}
        releaseName: nextcloud
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/nextcloud
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "job.nextcloud.maintenance.image"
            value: {{ .Values.nextcloud.fpm.version }}
        releaseName: nextcloud-addition
        valueFiles:
          - ./values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
