apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: helm-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: {{ .Values.certmanager.version }}
      helm:
        releaseName: cert-manager
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/cert-manager
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "clusterIssuer.certmanager.email"
            value: {{ .Values.certmanager.clusterIssuer.email }}
        releaseName: cert-manager-addition
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
