apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-cert-manager-cloudflare
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager-cloudflare
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: {{ .Values.certmanager.version }}
      helm:
        releaseName: cert-manager
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/cert-manager
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "clusterIssuer.certmanager.email"
            value: {{ .Values.certmanager.clusterIssuer.email }}
          - name: "secret.cloudflare.apiToken"
            value: {{ .Values.certmanager.secret.cloudflare.apiToken }}
          - name: "secret.cloudflareDyndns.env"
            value: {{ .Values.certmanager.secret.cloudflareDyndns.env | quote }}
          - name: "secret.cloudflareDyndns.authKey"
            value: {{ .Values.certmanager.secret.cloudflareDyndns.authKey | quote }}
          - name: "secret.cloudflareDyndns.dnsZoneId"
            value: {{ .Values.certmanager.secret.cloudflareDyndns.dnsZoneId | quote }}
        releaseName: cert-manager-addition
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
