apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hashicorp-vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hashicorp-vault
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: {{ .Values.vault.version }}
      helm:
        valueFiles:
          - $values/charts/hashicorp-vault/values.yaml
        parameters:
          - name: "server.ingress.annotations.clbipam.cilium\\.io/ips"
            value: {{ .Values.vault.server.ingress.annotations.lbipamCiliumIoIps }}
          - name: "server.ingress.hosts[0].host"
            value: "{ {{ .Values.vault.server.ingress.hosts0.host }} }"
          - name: "server.ingress.tls[0].hosts"
            value: { {{ .Values.vault.server.ingress.tls0.hosts }} }
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
