apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: helm-hassio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hassio
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/hassio/secrets
      # targetRevision: {{ .Values.spec.source.targetRevision }}
      targetRevision: sealed-secrets

    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/hassio
      # targetRevision: {{ .Values.spec.source.targetRevision }}
      targetRevision: sealed-secrets
      helm:
        releaseName: hassio
        valueFiles:
          - ./values.yaml
        valuesFrom:
          - kind: Secret
            name: hassio-ingress-secret
            valuesKey: ingress-host
            targetPath: ingress.host
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
