apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: {{ .Values.sealedSecrets.version }}
      helm:
        valueFiles:
          - $values/charts/sealed-secrets/values.yaml
        # parameters:
        #   - name: "ingress.hostname"
        #     value: {{ .Values.sealedSecrets.hostname }}
        releaseName: sealed-secrets
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:steled/argocd-apps.git
    #   path: ./charts/sealed-secrets
    #   targetRevision: {{ .Values.spec.source.targetRevision }}
    #   helm:
    #     parameters:
    #       - name: "secret.awsAccessKeyId"
    #         value: {{ .Values.sealed-secrets.secret.awsAccessKeyId }}
    #       - name: "secret.awsSecretAccessKey"
    #         value: {{ .Values.sealed-secrets.secret.awsSecretAccessKey }}
    #       - name: "secret.awsEndpoints"
    #         value: {{ .Values.sealed-secrets.secret.awsEndpoints }}
    #     releaseName: sealed-secrets-addition
    #     valueFiles:
    #       - ./values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
