apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-cert-manager-cloudflare
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-cert-manager-cloudflare
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: {{ .Values.cert-manager.version }}
      helm:
        valueFiles:
          - $values/charts/cert-manager/values.yaml
        parameters:
          - name: "certmanager.email"
            value: {{ .Values.certmanager.email }}
          - name: "cloudflare.apiToken"
            value: {{ .Values.certmanager.cloudflare.apiToken }}
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
