apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: helm-sealed-secrets-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: sealed-secrets-web
      repoURL: https://charts.bakito.net
      targetRevision: {{ .Values.sealedSecretsWeb.version }}
      helm:
        valueFiles:
          - $values/charts/sealed-secrets-web/values.yaml
        releaseName: sealed-secrets-web
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/sealed-secrets-web
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "httproute.hostnames0"
            value: {{ .Values.sealedSecretsWeb.httproute.hostnames0 }}
        releaseName: sealed-secrets-web-addition
        valueFiles:
          - ./values.yaml
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
