apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-victoriametrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoriametrics
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: {{ .Values.victoriametrics.version }}
      helm:
        valueFiles:
          - $values/charts/victoriametrics/values.yaml
        parameters:
          - name: "vmsingle.ingress.hosts"
            value: {{ .Values.victoriametrics.vmsingle.ingress.hosts }}
          - name: "vmsingle.ingress.tls[0].hosts"
            value: {{ .Values.victoriametrics.vmsingle.ingress.tls[0].hosts }}
          - name: "alertmanager.ingress.hosts"
            value: {{ .Values.victoriametrics.alertmanager.ingress.hosts }}
          - name: "alertmanager.ingress.tls[0].hosts"
            value: {{ .Values.victoriametrics.alertmanager.ingress.tls[0].hosts }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].bot_token"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.bot_token }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].chat_id"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.chat_id }}
          - name: "vmalert.ingress.hosts"
            value: {{ .Values.victoriametrics.vmalert.ingress.hosts }}
          - name: "vmalert.ingress.tls[0].hosts"
            value: {{ .Values.victoriametrics.vmalert.ingress.tls[0].hosts }}
          - name: "vmagent.ingress.hosts"
            value: {{ .Values.victoriametrics.vmagent.ingress.hosts }}
          - name: "vmagent.tls[0].hosts"
            value: {{ .Values.victoriametrics.vmagent.tls[0].hosts }}
          - name: "grafana.ingress.hosts"
            value: {{ .Values.victoriametrics.grafana.ingress.hosts }}
          - name: "grafana.tls[0].hosts"
            value: {{ .Values.victoriametrics.grafana.tls[0].hosts }}
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
