apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-victoriametrics-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # namespace: prometheus-operator
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: prometheus-operator-crds
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: {{ .Values.victoriametricsOperator.version }}
      helm:
        releaseName: prometheus-operator-crds
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true
