apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: ./charts/minio
    repoURL: git@github.com:steled/argocd-apps.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "endpoint.minio.ip"
          value: {{ .Values.minio.endpoint.minio.ip }}
        - name: "ingress.minio.host0"
          value: {{ .Values.minio.ingress.minio.host0 }}
        - name: "ingress.minio.tls0.hosts0"
          value: {{ .Values.minio.ingress.minio.tls0.hosts0 }}
        - name: "endpoint.minioConsole.ip"
          value: {{ .Values.minio.endpoint.minioConsole.ip }}
        - name: "ingress.minioConsole.host0"
          value: {{ .Values.minio.ingress.minioConsole.host0 }}
        - name: "ingress.minioConsole.tls0.hosts0"
          value: {{ .Values.minio.ingress.minioConsole.tls0.hosts0 }}
      releaseName: apprise
      valueFiles:
        - $values/charts/minio/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
