apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: helm-hassio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hassio
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: ./charts/hassio
    repoURL: git@github.com:steled/argocd-apps.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "httproute.hostnames0"
          value: {{ .Values.hassio.httproute.hostnames0 }}
      releaseName: hassio
      valueFiles:
        - $values/charts/hassio/values.yaml
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
