apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: helm-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: ./charts/minio
    repoURL: git@github.com:steled/argocd-apps.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "httproute.minio.hostnames0"
          value: {{ .Values.minio.httproute.minio.hostnames0 }}
        - name: "httproute.minioConsole.hostnames0"
          value: {{ .Values.minio.httproute.minioConsole.hostnames0 }}
      releaseName: minio
      valueFiles:
        - $values/charts/minio/values.yaml
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
