apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-jd-sftp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jd-sftp-test
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - path: ./charts/jd-sftp
      repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "secret.jd.env_devicename"
            value: {{ .Values.jdSftp.secret.jd.env_devicename }}
          - name: "secret.jd.env_email"
            value: {{ .Values.jdSftp.secret.jd.env_email }}
          - name: "secret.jd.env_password"
            value: {{ .Values.jdSftp.secret.jd.env_password }}
          - name: "sftp-server.sftp_ip_address"
            value: {{ .Values.jdSftp.sftpServer.sftp_ip_address }}
        valueFiles:
          - $values/charts/hassio/values.yaml
    - repoURL: https://github.com/steled/sftp-server.git
      # repoURL: https://github.com/steled/sftp-server/archive/refs/tags/{{ .Values.sftpServer.version }}.tar.gz
      targetRevision: {{ .Values.sftpServer.version }}
      helm:
        valueFiles:
          - $values/charts/jd-sftp/values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
