apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: helm-victoriametrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoriametrics
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: {{ .Values.victoriametrics.version }}
      helm:
        releaseName: victoria-metrics-k8s-stack
        parameters:
          - name: "alertmanager.route.hostnames[0]"
            value: {{ .Values.victoriametrics.alertmanager.route.hostnames0 }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].bot_token"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.bot_token }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].chat_id"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.chat_id }}
          - name: "vmagent.route.hostnames[0]"
            value: {{ .Values.victoriametrics.vmagent.route.hostnames0 }}
          - name: "vmalert.route.hostnames[0]"
            value: {{ .Values.victoriametrics.vmalert.route.hostnames0 }}
          - name: "vmalert.spec.extraArgs.external\\.url"
            value: "https://{{ .Values.victoriametrics.grafana.httproute.hostnames0 }}"
          - name: "vmsingle.route.hostnames[0]"
            value: {{ .Values.victoriametrics.vmsingle.route.hostnames0 }}
        valueFiles:
          - $values/charts/victoriametrics/victoriametrics-values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/victoriametrics
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "metricsProxy.image.version"
            value: {{ .Values.victoriametrics.metricsProxy.image.version }}
          - name: "grafana.httproute.hostnames0"
            value: {{ .Values.victoriametrics.grafana.httproute.hostnames0 }}
        releaseName: victoriametrics-addition
        valueFiles:
          - ./victoriametrics-addition-values.yaml
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
