apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-victoriametrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoriametrics
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: {{ .Values.victoriametrics.version }}
      helm:
        releaseName: victoria-metrics-k8s-stack
        parameters:
          - name: "alertmanager.ingress.hosts[0]"
            value: {{ .Values.victoriametrics.alertmanager.ingress.hosts0 }}
          - name: "alertmanager.ingress.tls[0].hosts[0]"
            value: {{ .Values.victoriametrics.alertmanager.ingress.tls0.hosts0 }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].bot_token"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.bot_token }}
          - name: "alertmanager.config.receivers[0].telegram_configs[0].chat_id"
            value: {{ .Values.victoriametrics.alertmanager.config.receivers.telegram_configs.chat_id }}
          - name: "grafana.ingress.hosts[0]"
            value: {{ .Values.victoriametrics.grafana.ingress.hosts0 }}
          - name: "grafana.ingress.tls[0].hosts[0]"
            value: {{ .Values.victoriametrics.grafana.tls0.hosts0 }}
          - name: "vmagent.ingress.hosts[0]"
            value: {{ .Values.victoriametrics.vmagent.ingress.hosts0 }}
          - name: "vmagent.ingresstls[0].hosts[0]"
            value: {{ .Values.victoriametrics.vmagent.tls0.hosts0 }}
          - name: "vmalert.ingress.hosts[0]"
            value: {{ .Values.victoriametrics.vmalert.ingress.hosts0 }}
          - name: "vmalert.ingress.tls[0].hosts[0]"
            value: {{ .Values.victoriametrics.vmalert.ingress.tls0.hosts0 }}
          - name: "vmsingle.ingress.hosts[0]"
            value: {{ .Values.victoriametrics.vmsingle.ingress.hosts0 }}
          - name: "vmsingle.ingress.tls[0].hosts[0]"
            value: {{ .Values.victoriametrics.vmsingle.ingress.tls0.hosts0 }}
        valueFiles:
          - $values/charts/victoriametrics/victoriametrics-values.yaml
          # - ./values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/victoriametrics
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "metricsProxy.image.version"
            value: {{ .Values.victoriametrics.metricsProxy.image.version }}
          - name: "secret.grafanaAdminPassword"
            value: {{ .Values.victoriametrics.secret.grafanaAdminPassword }}
          - name: "secret.grafanaAdminUser"
            value: {{ .Values.victoriametrics.secret.grafanaAdminUser }}
        releaseName: victoriametrics-addition
        valueFiles:
          - ./victoriametrics-addition-values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
