apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-cert-manager-cloudflare
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-cert-manager-cloudflare
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: helm-cert-manager-cloudflare
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
