apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-jd-sftp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jd-sftp
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: jdownloader2
      repoURL: https://pmoscode-helm.github.io/jdownloader2/
      targetRevision: {{ .Values.jdownloader2.version }}
      helm:
        releaseName: jdownloader2
        parameters:
          - name: "image.tag"
            value: {{ .Values.jdownloader2.image.version }}
        valueFiles:
          - $values/charts/jd-sftp/jdownloader2/values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/jd-sftp/jdownloader2
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        releaseName: jdownloader2-addition
    - chart: sftp-server
      repoURL: https://sj14.github.io/helm-charts
      targetRevision: {{ .Values.sftpServer.version }}
      helm:
        releaseName: sftp-server
        parameters:
          - name: "image.tag"
            value: {{ .Values.sftpServer.image.version }}
          # - name: "service.annotations.lbipam\\.cilium\\.io/ips"
          #   value: {{ .Values.jdSftp.sftpServer.service.annotations.lbipamCiliumIoIps }}
        valueFiles:
          - $values/charts/jd-sftp/sftp-server/values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
