apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: helm-jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jellyfin
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: {{ .Values.jellyfin.version }}
      helm:
        valueFiles:
          - $values/charts/jellyfin/values.yaml
        parameters:
          - name: "httproute.hostnames0"
            value: {{ .Values.jellyfin.httproute.hostnames0 }}
          - name: "ingress.hosts[0].host"
            value: {{ .Values.jellyfin.ingress.hosts0.host }}
          - name: "ingress.tls[0].hosts[0]"
            value: {{ .Values.jellyfin.ingress.tls0.hosts0 }}
        releaseName: jellyfin
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/jellyfin
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        releaseName: jellyfin-addition
        valueFiles:
          - ./values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
