apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: helm-homarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homarr
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - repoURL: oci://ghcr.io/homarr-labs/charts/homarr
      path: .
      targetRevision: {{ .Values.homarr.version }}
      helm:
        parameters:
          - name: "httproute.hostnames[0]"
            value: {{ .Values.homarr.httproute.hostnames0 }}
        releaseName: homarr
        valueFiles:
          - $values/charts/homarr/values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/homarr
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        releaseName: homarr-addition
        parameters:
          - name: "httproute.hostnames0"
            value: {{ .Values.homarr.httproute.hostnames0 }}
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
      prune: true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

  patches:
    - target:
        kind: Deployment
        name: homarr
      patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: homarr
        spec:
          template:
            spec:
              volumes:
                - name: nginx-etc
                  emptyDir: {}
                - name: nginx-lib
                  emptyDir: {}
                - name: nginx-cache
                  emptyDir: {}
                - name: nginx-log
                  emptyDir: {}
              containers:
                - name: homarr
                  volumeMounts:
                    - name: nginx-etc
                      mountPath: /etc/nginx
                    - name: nginx-lib
                      mountPath: /var/lib/nginx
                    - name: nginx-cache
                      mountPath: /var/cache/nginx
                    - name: nginx-log
                      mountPath: /var/log/nginx
    - target:
        kind: Deployment
        name: homarr
      patch: |
        spec:
          template:
            spec:
              volumes:
                - name: nginx-template
                  configMap:
                    name: homarr-nginx-template
              containers:
                - name: homarr
                  volumeMounts:
                    - name: nginx-template
                      mountPath: /etc/nginx/templates
                      readOnly: true
