apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-jd-sftp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jd-sftp
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - path: ./charts/jd-sftp
      repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "jd.secret.env_devicename"
            value: {{ .Values.jdSftp.jd.secret.env_devicename }}
          - name: "jd.secret.env_email"
            value: {{ .Values.jdSftp.jd.secret.env_email }}
          - name: "jd.secret.env_password"
            value: {{ .Values.jdSftp.jd.secret.env_password }}
        valueFiles:
          - $values/charts/hassio/values.yaml
    - chart: sftp-server
      repoURL: https://sj14.github.io/helm-charts
      targetRevision: {{ .Values.sftpServer.version }}
      helm:
        releaseName: sftp-server
        parameters:
          - name: "image.tag"
            value: {{ .Values.sftpServer.image.version }}
          - name: "service.annotations.lbipam\\.cilium\\.io/ips"
            value: {{ .Values.jdSftp.sftpServer.service.annotations.lbipamCiliumIoIps }}
        valueFiles:
          - $values/charts/jd-sftp/values.yaml
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
