apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn
    server: {{ .Values.spec.destination.server }}
  project: apps
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: {{ .Values.longhorn.version }}
      helm:
        valueFiles:
          - $values/charts/longhorn/values.yaml
        parameters:
          - name: "ingress.host"
            value: {{ .Values.longhorn.host }}
        releaseName: longhorn
    - repoURL: git@github.com:steled/argocd-apps.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:steled/argocd-apps.git
      path: ./charts/longhorn
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        parameters:
          - name: "secret.awsAccessKeyId"
            value: {{ .Values.longhorn.secret.awsAccessKeyId }}
          - name: "secret.awsSecretAccessKey"
            value: {{ .Values.longhorn.secret.awsSecretAccessKey }}
          - name: "secret.awsEndpoints"
            value: {{ .Values.longhorn.secret.awsEndpoints }}
        releaseName: longhorn-addition
        valueFiles:
          - ./values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
