fileStorage:
  local:
    persistence:
      enabled: true
      storageClass: longhorn

secretKeyExternalSecret:
  # -- This is for setting up the secret key external secret name.
  name: outline
  # -- This is for setting up the secret key external secret key.
  key: secret-key

strategy:
  type: Recreate

smtp:
  host: ""
  port: 587
  fromEmail: ""
  replyEmail: ""
  tlsCiphers: ""
  secure: false
  existingSecret:
    name: outline
    usernameKey: smtp-username
    passwordKey: smtp-password

postgresql:
  enabled: true
  auth:
    username: outline
  backup:
    enabled: true
    cronjob:
      networkPolicy:
        enabled: true
      schedule: "@hourly"
      storage:
        enabled: true
        # resourcePolicy: keep
        size: 10Gi
        storageClass: longhorn

  global:
    defaultStorageClass: longhorn
    postgresql:
      auth:
        database: outline
        existingSecret: outline
        secretKeys:
          adminPasswordKey: postgresql-admin-password
          userPasswordKey: password

  primary:
    networkPolicy:
      enabled: true
      extraIngress:
        # needed for istio in ambient mode
        - ports:
          - port: 15008
            protocol: TCP
    persistence:
      enabled: true
      storageClass: longhorn
    resourcesPreset: small

externalPostgresql:
  existingSecret: outline

redis:
  enabled: true
  auth:
    existingSecret: outline
    existingSecretPasswordKey: redis-password
  global:
    defaultStorageClass: longhorn
  # needed for istio, see: https://github.com/bitnami/charts/issues/31394
  networkPolicy:
    enabled: true
    extraIngress:
        - ports:
            - port: 15008
  master:
    persistence:
      enabled: false
      storageClass: longhorn
    resourcesPreset: "micro"
  # replica:
  #   persistence:
  #     enabled: true
  #     storageClass: longhorn
  #   replicaCount: 1
  #   resourcesPreset: "micro"

externalRedis:
  existingSecret: outline
  usernameSecretKey: redis-username
  passwordSecretKey: redis-password