existingSecret: hedgedoc
extraEnv:
  CMD_ALLOW_ANONYMOUS: false
  CMD_ALLOW_ANONYMOUS_EDITS: false
  CMD_DOMAIN: ''
  CMD_LOGLEVEL: debug
  CMD_PROTOCOL_USESSL: true
gatewayApi:
  enabled: true
  parentRefs:
    - name: shared-gateway
      namespace: istio-system
persistence:
  storageClass: longhorn

postgresql:
  enabled: true
  auth:
    database: hedgedoc
    password: ''
    username: hedgedoc
    existingSecret: hedgedoc
    secretKeys:
      adminPasswordKey: postgresql-admin-password
      userPasswordKey: postgresql-user-password
