existingSecret: hedgedoc-chart
extraEnv:
  CMD_DOMAIN: ''
  CMD_LOGLEVEL: debug
gatewayApi:
  enabled: true
  parentRefs:
    - name: shared-gateway
      namespace: istio-system

postgresql:
  enabled: true
  auth:
    database: hedgedoc
    password: ''
    username: hedgedoc
