---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: myjd
spec:
  encryptedData:
    email: AgA/3Ck8leyO05r6v1+41i+Vm5NKXN8uPbJ4tPcHc0cLrs6TLcJR5nGKD04YUvKssaAWylhovu5zmYqX4QpNJdLtDNaXUiJpfc5+fiM17nRf7KGexObbjEW0IE9YiBuqxx9bzn1KR2bwsRFi5nHj3j5LSrCa8G6z1XipSTdJk/hzYFyChZYo9QbnxwDFuSvG/p5okP/uCNM1TPgdrvdbe7MiD8LL3up8SYVSUFJRlux4znT0txkV9Rl2WPuIyedFz1lAaDrDTb6fYzaeBa3/BoUpZCmHkVAruMOFFeR86aFNlJBh81HeY8gN8CTtel8KSEJ/iwuTsWaTD4niKPyOC9DCNDNeTS5EYwFyN7JCudIJrz7Mjohxl17D1p7o5jJ+48ZUmHKvWICsXrL5TKCQamoT1nPnicZ+fHD/kZ1nA55391d11m/93PDF7F2EQ9yxCja6PibpKB/ZcGKiyuPFJR7lgtONDshkRoFyDHPR0zMpc54rMI8xrSgcWN9q25KMhOpipu8jJXxC0q1UKTOs0WSauexlesFHRmG7DN/m8ioCrfnhiqSJM3vhKhvzWdJ7Rj2VTcHDFoFA6eH6rqIef34POEHIU7fbmC+evJAVyVcWyNtwnd9CN6DXXH2ZUPnAgZnBCVMFaesUlPDbo7JjvwF63aPuWU3nhZKl1tPkG3otobc2inBBIBMSpovCJ8kHZRfu4XQrdV2umo97sQ==
    password: AgA5oBZI9BJfY/3L0ZFVE1dKpjMpBTYOWRUQtqrwpt8Nydr4aEM4Lk+uZIJiCqqwuvMysCWxOVAjYVB7X0fKEsI730KBZJL74I5bmWVZQSJXNLzuWzoO4atqcprO7lPlt2D75haU6Fo7j0iZZhWs5nRJoQzZIsBb55EUXAkUeUWylV3NjwYl/Vi6TYnXQoGoxgwbcyPRpY7a6iaSvZ8UfMsnun7LT5HG3qbohpeoPSAQjr8hfyY+lWgeRft6pau0GLemuctpf1pIlyp+2tSG2x+1gkJ15iS/yV4Lhq/opQMWcA9HzwWL9vQXrZ5DNtsQHHYb+NG/spEveHkAhLUcpbjg3ZdWcoJAZ8hudp4lr7IEIm7kpCHowmsmGwNO99PCHbKbJWBwYPmvwcgZOg6IuMjJ70+iewgQb7haxpExrJ0TRu5R3UuEQ4TQn9KoRLKnJcIcQWNHG/dOosHd3dYtaAe0+oa3mPkOPReTfRZAkX54g3vpajHW8aQiXGBprX1I2bHVW7HlgQtr/CPSu3B11xP8SFu7FfB1bNqP61ibk/XSZ7LTvOSkSS2icXQ1FLxhz8vs7uarqJftJ7rSkP70MbJMK64w4Vyz3o1xXSYycMUGLy+Qo4i89yxk+Opou6hIFiFyz4B7ITsC+lKJEKrDbd4MqS/3vjjiRLl0Pf1zWrF1Rl0VlwDVXHWZlR0QVNDdzlGzwTYw+gvlSw==
  template:
    metadata:
      name: myjd
      namespace: jd-sftp
