apiVersion: v1
kind: Endpoints
metadata:
  name: minio
subsets:
- addresses:
  - ip: "172.16.4.26"
  ports:
  - name: http
    port: 9000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-console
subsets:
- addresses:
  - ip: "172.16.4.26"
  ports:
  - name: http
    port: 9001
    protocol: TCP
