apiVersion: v1
kind: Endpoints
metadata:
  name: minio
subsets:
- addresses:
  - ip: {{ .Values.endpoint.minio.ip }}
  ports:
  - name: http
    port: 9000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-console
subsets:
- addresses:
  - ip: {{ .Values.endpoint.minioConsole.ip }}
  ports:
  - name: http
    port: 9001
    protocol: TCP
