apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-{{ .Values.ingress.minio.environment }}
    ingress.cilium.io/loadbalancer-mode: shared
  name: minio
spec:
  ingressClassName: cilium
  rules:
  - host: {{ .Values.ingress.minio.host0 }}
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.minio.tls0.hosts0 }}
    secretName: minio-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-{{ .Values.ingress.minioConsole.environment }}
    ingress.cilium.io/loadbalancer-mode: shared
  name: minio-console
spec:
  ingressClassName: cilium
  rules:
  - host: {{ .Values.ingress.minioConsole.host0 }}
    http:
      paths:
      - backend:
          service:
            name: minio-console
            port:
              number: 9001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.minioConsole.tls0.hosts0 }}
    secretName: minio-console-tls
