apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
  name: minio-secret
type: Opaque
data:
  rootPassword: {{ .Values.secret.rootPassword | b64enc }}
  rootUser: {{ .Values.secret.rootUser | b64enc }}
  user1_password: {{ .Values.secret.user1_password | b64enc }}
  user1_secretKey: {{ .Values.secret.user1_secretKey | b64enc }}
