apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: 9001
  type: ClusterIP
