{{- if .Values.secret.htpasswd }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: apprise
  name: apprise-api-override-conf-config
data:
  location-override.conf: |
    auth_basic            "Apprise API Restricted Area";
    auth_basic_user_file  /etc/nginx/.htpasswd;
{{ end }}
