apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: apprise
  name: apprise-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
