apiVersion: v1
kind: Service
metadata:
  labels:
    app: apprise
  name: apprise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: apprise
  type: ClusterIP
