---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgB8UBWQgU+G1gyrSa+ZyUbj8jhQZHcqTNaHRdn1t/QLts0vsgj2510EkoGNUDvIa5llR7Xz5Y8Dahiba8QKmT+jFG02El50ofiTZgEFYyIVPbd8sw0FOpyS9jyrWMgLGjeYb5q9aDxUp/B+YxeX0i7Lv/B2fTm56k5MU4K/rUqd0xfIdDa7ZWLazJQ1j495Y3Khvh1jYWfnrEz6JyTV+MKbsYK8gQtQZLBq6GJS6lTlhdC9R2J1v7Xn4t7W5Ovj8gFudNSAUhS72BOibJlvxK6hdBZK2wv7QSCjxQfzDXk18bbWJMvKf7pQ+VanUvP6RZoK3lVCq7jmag4QbTKEDNnlkd5rxzGBKcw1kuIfPMW8XSVBLfIQGkhnS0cp026R/vBD+TSOM7L9C+UYs9NklzvmBHtCbiqqgIc0Zlo5Q2gj593AwzO9o5fPTGyLFJwbDVpQjDEmwbbzWbs8TFFTKit1wjopq6qP2fru3sLNh7OHXB2Nomm4zugvyPpA4wH6rvzBBMAbnP+l3ipr6XF7rFOsyZWkgxd5sLJxgNjKbyvMu01Imj3gr7JR+elORNOHSCAMUpxLnWk0OXko2O6+ZvxRFd834PjXE9ebXcW2eHUkNV8dUX9CjolBUQF7cAVLt/669TVTbLlI9jtyRnkd0BSGJL5TD3jKKBD7ERyTo39wfJtKbG+qT95yIvTLM+n/w+9YR5D0mzLbhNhzcFXjsAlCs68DybDgy3zU5Sr5epDTFumY3uEtwuDD
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
