apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-sftp-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.jd.pvc.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-sftp-downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.jd.pvc.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-sftp-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.jd.pvc.storageClassName }}
